services:
  #Copying payara sdk application server to payara-sdk folder - unnecessary if you already have a payara copy
  payara-sdk-export:
    container_name: payara-sdk-exporter
    image: payara/server-full:6.2025.8-jdk17
    user: "0:0"
    entrypoint: [ "/bin/sh","-lc" ]
    command:
    - >
      if [ -x /sdk/appserver/bin/asadmin ]; then
            echo "[sdk export] appserver already exists, skip"; exit 0;
      fi;
      echo "[sdk export] copying /opt/payara/appserver -> /sdk ...";
      cp -a /opt/payara/appserver /sdk/ && echo "[export] done"
    volumes:
      - ./payara-sdk:/sdk:rw
    restart: "no"

  #Payara server
  payara:
    container_name: payara
    image: payara/server-full:6.2025.8-jdk17
    env_file: .env
    environment:
      SECURE_ADMIN: "true"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - "8080:8080"   #apps
      - "4848:4848"   #admin
      - "${DEBUG_PORT}:${DEBUG_PORT}"   #debug JDWP
    volumes:
      #Directly mounting settings to the server config -> needs a restart
      - ./docker/pre-boot-commands.asadmin:/opt/payara/config/pre-boot-commands.asadmin:ro
      #Can drop .war in the folder for auto deploy but not necessary
      - ./deploy:/opt/payara/appserver/glassfish/domains/domain1/autodeploy
      #Workspace volumes
      - ${SERVICE_HOST_PATH}:/workspace-service
      - ${WEBAPP_HOST_PATH}:/workspace-webapp

volumes:
  db_data:
