services:
  #Payara server
  payara:
    container_name: payara
    image: payara/server-full:6.2025.8-jdk17
    env_file: .env
    environment:
      SECURE_ADMIN: "true"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - "8080:8080"   #apps
      - "4848:4848"   #admin
      - "${DEBUG_PORT}:${DEBUG_PORT}"   #debug JDWP
    volumes:
      #Directly mounting settings to the server config -> needs a restart
      - ./docker/pre-boot-commands.asadmin:/opt/payara/config/pre-boot-commands.asadmin:ro
      #auto deploy (maps local target artefact to container) - You must have StudyBuddyService and StudyBuddyWebapp projects at the same file system level
      - ./target/StudyBuddyService-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/StudyBuddyService-1.0-SNAPSHOT.war
      - ../StudyBuddyWebapp/target/StudyBuddyWebapp-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/StudyBuddyWebapp-1.0-SNAPSHOT.war